permalink: /:title/
exclude: ["README.md", "bin", ".gitignore", "blog.sublime-project"]
production_url : http://sergiolopes.org

markdown: kramdown
pygments: true

title: sergiolopes.org
author:
   name: Sérgio Lopes